/** @typedef {'professor'|'phd'|'postdoc'|'researcher'|'research_scientist'|'industry_researcher'} DemoRole */

const INSTITUTIONS = {
  mit: {
    id: 'massachusetts-institute-of-technology',
    name: 'Massachusetts Institute of Technology',
  },
  stanford: { id: 'stanford-university', name: 'Stanford University' },
  berkeley: {
    id: 'university-of-california-berkeley',
    name: 'University of California, Berkeley',
  },
  cambridge: { id: 'university-of-cambridge', name: 'University of Cambridge' },
  harvard: { id: 'harvard-university', name: 'Harvard University' },
};

const U = {
  profRivera: 'erudis_demo_prof_rivera',
  profChen: 'erudis_demo_prof_chen',
  profBell: 'erudis_demo_prof_bell',
  phdKim: 'erudis_demo_phd_kim',
  phdSantos: 'erudis_demo_phd_santos',
  postdocLee: 'erudis_demo_postdoc_lee',
  researcherWalsh: 'erudis_demo_researcher_walsh',
  sciPatel: 'erudis_demo_sci_patel',
  adminMit: 'erudis_demo_inst_admin_mit',
};

const INSTITUTION_DOCS = [
  {
    id: INSTITUTIONS.mit.id,
    name: INSTITUTIONS.mit.name,
    logoUrl: '',
    coverUrl: '',
    description: 'Demo institution profile for MIT on THE ERUDIS.',
    websiteUrl: 'https://web.mit.edu',
    adminUserIds: ['erudis_demo_inst_admin_mit'],
  },
  {
    id: INSTITUTIONS.stanford.id,
    name: INSTITUTIONS.stanford.name,
    logoUrl: '',
    coverUrl: '',
    description: '',
    websiteUrl: 'https://www.stanford.edu',
    adminUserIds: [],
  },
  {
    id: INSTITUTIONS.berkeley.id,
    name: INSTITUTIONS.berkeley.name,
    logoUrl: '',
    coverUrl: '',
    description: '',
    websiteUrl: 'https://www.berkeley.edu',
    adminUserIds: [],
  },
  {
    id: INSTITUTIONS.cambridge.id,
    name: INSTITUTIONS.cambridge.name,
    logoUrl: '',
    coverUrl: '',
    description: '',
    websiteUrl: 'https://www.cam.ac.uk',
    adminUserIds: [],
  },
  {
    id: INSTITUTIONS.harvard.id,
    name: INSTITUTIONS.harvard.name,
    logoUrl: '',
    coverUrl: '',
    description: '',
    websiteUrl: 'https://www.harvard.edu',
    adminUserIds: [],
  },
];

const LAB = {
  mit: 'erudis_demo_lab_mit_rivera',
  stanford: 'erudis_demo_lab_stanford_chen',
  berkeley: 'erudis_demo_lab_berkeley_bell',
};

const USERS = [
  {
    uid: U.adminMit,
    name: 'Alex Morgan',
    email: 'alex.morgan.admin@mit.edu',
    role: 'institution_admin',
    institutionId: INSTITUTIONS.mit.id,
    institutionName: INSTITUTIONS.mit.name,
    labOnboardingIntent: 'defer',
    labIds: [],
    primaryLabId: null,
    researchAreas: ['Higher Education'],
    following: [],
    followers: [],
    bio: 'MIT institution administrator (demo). Manages labs and researchers at MIT.',
    openToWork: [],
    subscription: 'pro',
    openToCollaborate: false,
    collaborationTypes: [],
  },
  {
    uid: U.profRivera,
    name: 'Dr. Elena Rivera',
    email: 'elena.rivera.demo@mit.edu',
    role: 'professor',
    institutionId: INSTITUTIONS.mit.id,
    institutionName: INSTITUTIONS.mit.name,
    labOnboardingIntent: 'create_lab',
    labIds: [LAB.mit],
    primaryLabId: LAB.mit,
    researchAreas: ['Computer Science', 'AI/ML'],
    following: [U.profChen, U.phdKim, U.postdocLee],
    followers: [U.phdKim, U.phdSantos, U.postdocLee, U.researcherWalsh],
    bio: 'Professor of adaptive systems. Demo profile for THE ERUDIS staging.',
    openToWork: ['faculty_positions', 'postdoc_positions'],
    subscription: 'pro',
    labNoteStoryPortrait: 'apple',
  },
  {
    uid: U.profChen,
    name: 'Dr. James Chen',
    email: 'james.chen.demo@stanford.edu',
    role: 'professor',
    institutionId: INSTITUTIONS.stanford.id,
    institutionName: INSTITUTIONS.stanford.name,
    labOnboardingIntent: 'create_lab',
    labIds: [LAB.stanford],
    primaryLabId: LAB.stanford,
    researchAreas: ['Artificial Intelligence', 'Natural Language Processing'],
    following: [U.profRivera, U.sciPatel, U.phdSantos],
    followers: [U.profRivera, U.phdSantos, U.sciPatel],
    bio: 'NLP lab PI — synthetic data for jobs and discover UI.',
    openToWork: ['postdoc_positions'],
    subscription: 'lab_pro',
    labNoteStoryPortrait: 'watermelon',
  },
  {
    uid: U.profBell,
    name: 'Dr. Amara Bell',
    email: 'amara.bell.demo@berkeley.edu',
    role: 'professor',
    institutionId: INSTITUTIONS.berkeley.id,
    institutionName: INSTITUTIONS.berkeley.name,
    labOnboardingIntent: 'create_lab',
    labIds: [LAB.berkeley],
    primaryLabId: LAB.berkeley,
    researchAreas: ['Computational Biology', 'Statistics'],
    following: [U.profRivera, U.profChen],
    followers: [U.phdKim, U.sciPatel],
    bio: 'Quantitative biology group lead (demo).',
    openToWork: ['faculty_positions'],
    subscription: 'pro',
    labNoteStoryPortrait: 'orange',
  },
  {
    uid: U.phdKim,
    name: 'Jordan Kim',
    email: 'jordan.kim.demo@mit.edu',
    role: 'phd',
    institutionId: INSTITUTIONS.mit.id,
    institutionName: INSTITUTIONS.mit.name,
    labOnboardingIntent: 'join_lab',
    labIds: [LAB.mit],
    primaryLabId: LAB.mit,
    researchAreas: ['AI/ML', 'Computer Science'],
    following: [U.profRivera, U.postdocLee],
    followers: [U.profRivera, U.postdocLee],
    bio: 'Year 4 PhD — robust ML for science (staging copy).',
    openToWork: ['industry', 'postdoc_positions'],
    subscription: 'free',
    labNoteStoryPortrait: 'apple',
  },
  {
    uid: U.phdSantos,
    name: 'Maya Santos',
    email: 'maya.santos.demo@stanford.edu',
    role: 'phd',
    institutionId: INSTITUTIONS.stanford.id,
    institutionName: INSTITUTIONS.stanford.name,
    labOnboardingIntent: 'join_lab',
    labIds: [LAB.stanford],
    primaryLabId: LAB.stanford,
    researchAreas: ['Natural Language Processing'],
    following: [U.profChen, U.profRivera],
    followers: [U.profChen],
    bio: 'PhD student working on evaluation for LLM agents (demo).',
    openToWork: ['nothing_now'],
    subscription: 'free',
  },
  {
    uid: U.postdocLee,
    name: 'Dr. Priya Lee',
    email: 'priya.lee.demo@cam.ac.uk',
    role: 'postdoc',
    institutionId: INSTITUTIONS.cambridge.id,
    institutionName: INSTITUTIONS.cambridge.name,
    labOnboardingIntent: 'join_lab',
    labIds: [LAB.mit],
    primaryLabId: LAB.mit,
    researchAreas: ['Neuroscience', 'AI/ML'],
    following: [U.profRivera, U.profBell],
    followers: [U.profRivera, U.phdKim],
    bio: 'Postdoc bridging neuroscience and representation learning.',
    openToWork: ['faculty_positions', 'industry'],
    subscription: 'pro_write',
  },
  {
    uid: U.researcherWalsh,
    name: 'Chris Walsh',
    email: 'chris.walsh.demo@harvard.edu',
    role: 'researcher',
    institutionId: INSTITUTIONS.harvard.id,
    institutionName: INSTITUTIONS.harvard.name,
    labOnboardingIntent: 'defer',
    labIds: [],
    primaryLabId: null,
    researchAreas: ['Economics', 'Public Policy'],
    following: [U.profRivera, U.profChen, U.profBell],
    followers: [],
    bio: 'Independent research fellow exploring science policy (demo).',
    openToWork: ['collaboration'],
    subscription: 'free',
  },
  {
    uid: U.sciPatel,
    name: 'Dr. Ravi Patel',
    email: 'ravi.patel.demo@berkeley.edu',
    role: 'research_scientist',
    institutionId: INSTITUTIONS.berkeley.id,
    institutionName: INSTITUTIONS.berkeley.name,
    labOnboardingIntent: 'join_lab',
    labIds: [LAB.berkeley, LAB.stanford],
    primaryLabId: LAB.berkeley,
    researchAreas: ['Computational Biology', 'Data Science'],
    following: [U.profBell, U.profChen],
    followers: [U.profChen, U.profBell],
    bio: 'Staff scientist — pipelines and open data (demo).',
    openToWork: ['industry'],
    subscription: 'pro',
  },
];

const LABS = [
  {
    id: LAB.mit,
    name: 'Rivera Adaptive Systems Lab',
    institutionId: INSTITUTIONS.mit.id,
    institutionName: INSTITUTIONS.mit.name,
    department: 'EECS',
    websiteUrl: 'https://example.edu/rivera-lab',
    piId: U.profRivera,
    memberIds: [U.profRivera, U.phdKim, U.postdocLee],
    researchAreas: ['AI/ML', 'Computer Science', 'Robotics'],
    description:
      'We study **reliable learning** under distribution shift — with an emphasis on reproducible benchmarks and open tooling.',
    followers: [U.researcherWalsh],
  },
  {
    id: LAB.stanford,
    name: 'Chen Language & Reasoning Lab',
    institutionId: INSTITUTIONS.stanford.id,
    institutionName: INSTITUTIONS.stanford.name,
    department: 'Computer Science',
    piId: U.profChen,
    memberIds: [U.profChen, U.phdSantos, U.sciPatel],
    researchAreas: ['Natural Language Processing', 'Artificial Intelligence'],
    description:
      'Building **transparent** NLP systems: interpretability, evaluation, and human-in-the-loop science.',
    followers: [U.profRivera, U.researcherWalsh],
  },
  {
    id: LAB.berkeley,
    name: 'Bell Quantitative Biology Group',
    institutionId: INSTITUTIONS.berkeley.id,
    institutionName: INSTITUTIONS.berkeley.name,
    department: 'Integrative Biology',
    piId: U.profBell,
    memberIds: [U.profBell, U.sciPatel],
    researchAreas: ['Computational Biology', 'Statistics'],
    description:
      'Statistical models for **single-cell** and spatial omics — demo lab for hiring and papers UI.',
    followers: [],
  },
];

const POSTS = [
  {
    id: 'erudis_demo_post_01',
    authorId: U.profRivera,
    labId: LAB.mit,
    institutionId: INSTITUTIONS.mit.id,
    type: 'update',
    title: 'Fall seminar series — trustworthy ML',
    researchArea: 'Computer Science',
    tags: ['seminar', 'lab'],
    content:
      'Kicking off our **Thursday** seminar block: external speakers on calibration, auditing, and deployment. Open to MIT affiliates (demo announcement).',
    resonateCount: 14,
    viewCount: 220,
    hoursAgo: 4,
  },
  {
    id: 'erudis_demo_post_02',
    authorId: U.phdKim,
    labId: LAB.mit,
    institutionId: INSTITUTIONS.mit.id,
    type: 'result',
    title: 'Benchmark sweep: hardware matters',
    researchArea: 'AI/ML',
    tags: ['benchmarks', 'reproducibility'],
    content:
      'We documented a **12% latency swing** when the eval box was thermally throttled. Posting configs alongside scores.',
    resonateCount: 9,
    viewCount: 140,
    hoursAgo: 9,
  },
  {
    id: 'erudis_demo_post_03',
    authorId: U.profChen,
    labId: LAB.stanford,
    institutionId: INSTITUTIONS.stanford.id,
    type: 'paper',
    title: 'Preprint: sparse attention on long documents',
    researchArea: 'Natural Language Processing',
    tags: ['preprint', 'nlp'],
    content:
      'Draft on **arXiv** (demo only). We trade a small accuracy hit for predictable memory on 100k-token inputs. Feedback welcome.',
    resonateCount: 22,
    viewCount: 410,
    hoursAgo: 14,
  },
  {
    id: 'erudis_demo_post_04',
    authorId: U.phdSantos,
    labId: LAB.stanford,
    institutionId: INSTITUTIONS.stanford.id,
    type: 'question',
    title: 'Survey recommendations for agent evaluation?',
    researchArea: 'Artificial Intelligence',
    tags: ['reading', 'agents'],
    content:
      'Looking for **post-2022** surveys covering tool-use benchmarks. What did your reading group use?',
    resonateCount: 5,
    viewCount: 88,
    hoursAgo: 20,
  },
  {
    id: 'erudis_demo_post_05',
    authorId: U.profBell,
    labId: LAB.berkeley,
    institutionId: INSTITUTIONS.berkeley.id,
    type: 'milestone',
    title: 'Grant renewal submitted',
    researchArea: 'Computational Biology',
    tags: ['funding'],
    content:
      'Team pulled together aims for **spatial transcriptomics** at scale. Fingers crossed for fall notification (demo text).',
    resonateCount: 11,
    viewCount: 95,
    hoursAgo: 28,
  },
  {
    id: 'erudis_demo_post_06',
    authorId: U.sciPatel,
    labId: LAB.berkeley,
    institutionId: INSTITUTIONS.berkeley.id,
    type: 'update',
    title: 'New public pipeline release',
    researchArea: 'Data Science',
    tags: ['open-science', 'tools'],
    content:
      'Released a **Nextflow** skeleton for our preprocessing stack. Docs in the lab wiki; issues on GitHub (placeholder).',
    resonateCount: 7,
    viewCount: 130,
    hoursAgo: 36,
  },
  {
    id: 'erudis_demo_post_07',
    authorId: U.postdocLee,
    labId: LAB.mit,
    institutionId: INSTITUTIONS.mit.id,
    type: 'idea',
    title: 'Hypothesis: coupling graphs with sparse attention',
    researchArea: 'Neuroscience',
    tags: ['graphs', 'hypothesis'],
    content:
      'Bias attention using the **graph Laplacian** so long-range hops are cheap only when topology supports them.',
    resonateCount: 8,
    viewCount: 76,
    hoursAgo: 48,
  },
  {
    id: 'erudis_demo_post_08',
    authorId: U.researcherWalsh,
    labId: null,
    institutionId: INSTITUTIONS.harvard.id,
    type: 'paper_review',
    title: 'Notes: science-of-science keynote themes',
    researchArea: 'Economics',
    tags: ['conference', 'policy'],
    content:
      'Three themes: **evaluation beyond accuracy**, dataset governance, and incentives for replication.',
    resonateCount: 4,
    viewCount: 62,
    hoursAgo: 60,
  },
  {
    id: 'erudis_demo_post_09',
    authorId: U.profRivera,
    labId: null,
    institutionId: INSTITUTIONS.mit.id,
    type: 'update',
    title: 'Hiring: postdoc in robust ML',
    researchArea: 'Computer Science',
    tags: ['hiring'],
    content:
      'We have an open **postdoc** slot (see Jobs). Strong systems + theory background preferred.',
    resonateCount: 16,
    viewCount: 300,
    hoursAgo: 72,
  },
  {
    id: 'erudis_demo_post_10',
    authorId: U.profChen,
    labId: LAB.stanford,
    institutionId: INSTITUTIONS.stanford.id,
    type: 'update',
    visibility: 'members_only',
    title: 'Lab-only: visitor policy update',
    researchArea: 'Artificial Intelligence',
    tags: ['lab-culture'],
    content:
      'Visitors need **48h** notice and a buddy from the lab. Members-only note for staging.',
    resonateCount: 2,
    viewCount: 18,
    hoursAgo: 80,
  },
  {
    id: 'erudis_demo_post_11',
    authorId: U.phdKim,
    labId: LAB.mit,
    institutionId: INSTITUTIONS.mit.id,
    type: 'milestone',
    title: 'Thesis proposal defended',
    researchArea: 'Computer Science',
    tags: ['thesis'],
    content:
      'Committee signed off on the **proposal**. Next: integrate wet-lab validation chapter feedback.',
    resonateCount: 19,
    viewCount: 105,
    hoursAgo: 96,
  },
  {
    id: 'erudis_demo_post_12',
    authorId: U.profBell,
    labId: null,
    institutionId: INSTITUTIONS.berkeley.id,
    type: 'question',
    title: 'Best practices for spatial deconvolution?',
    researchArea: 'Computational Biology',
    tags: ['methods'],
    content:
      'Comparing **cell2location** vs newer Bayesian approaches — what worked for your tissue atlas projects?',
    resonateCount: 6,
    viewCount: 91,
    hoursAgo: 120,
  },
];

const JOBS = [
  {
    id: 'erudis_demo_job_01',
    labId: LAB.mit,
    postedByUserId: U.profRivera,
    title: 'Postdoctoral Fellow — Robust Machine Learning',
    positionType: 'Postdoc',
    department: 'EECS',
    location: 'Cambridge, MA',
    remote: false,
    institutionName: INSTITUTIONS.mit.name,
    applicationUrl: 'https://example.edu/jobs/rivera-postdoc',
    deadline: '2026-09-30',
    sponsored: true,
    description:
      '**MIT (demo).** Join the Rivera lab on distributionally robust learning and reproducible benchmarks.',
  },
  {
    id: 'erudis_demo_job_02',
    labId: LAB.mit,
    postedByUserId: U.profRivera,
    title: 'PhD Position — Adaptive Systems',
    positionType: 'PhD Position',
    department: 'EECS',
    location: 'Cambridge, MA',
    remote: false,
    institutionName: INSTITUTIONS.mit.name,
    applicationUrl: null,
    deadline: '2026-12-15',
    sponsored: false,
    description:
      'Graduate admissions cycle **demo listing**. Strong math and coding background expected.',
  },
  {
    id: 'erudis_demo_job_03',
    labId: LAB.stanford,
    postedByUserId: U.profChen,
    title: 'PhD Student — NLP & Evaluation',
    positionType: 'PhD Position',
    department: 'Computer Science',
    location: 'Stanford, CA',
    remote: false,
    institutionName: INSTITUTIONS.stanford.name,
    applicationUrl: 'https://example.edu/stanford-phd-demo',
    deadline: '2026-11-01',
    sponsored: false,
    description:
      'Work on **transparent** NLP evaluation and human-in-the-loop science (staging copy).',
  },
  {
    id: 'erudis_demo_job_04',
    labId: LAB.stanford,
    postedByUserId: U.profChen,
    title: 'Research Scientist — Language Models',
    positionType: 'Research Scientist',
    department: 'Computer Science',
    location: 'Stanford, CA',
    remote: true,
    institutionName: INSTITUTIONS.stanford.name,
    applicationUrl: null,
    deadline: null,
    sponsored: true,
    description:
      'Staff scientist role (demo). Hybrid OK; focus on **data** and evaluation infrastructure.',
  },
  {
    id: 'erudis_demo_job_05',
    labId: LAB.berkeley,
    postedByUserId: U.profBell,
    title: 'Postdoc — Spatial Omics',
    positionType: 'Postdoc',
    department: 'Integrative Biology',
    location: 'Berkeley, CA',
    remote: false,
    institutionName: INSTITUTIONS.berkeley.name,
    applicationUrl: 'https://example.edu/berkeley-postdoc',
    deadline: '2026-08-01',
    sponsored: false,
    description:
      'Quantitative biology group seeking a postdoc with **statistics** and imaging experience.',
  },
  {
    id: 'erudis_demo_job_06',
    labId: null,
    postedByUserId: U.researcherWalsh,
    title: 'Research Fellow — Science Policy (Harvard)',
    positionType: 'Research Scientist',
    department: 'Kennedy School',
    location: 'Cambridge, MA',
    remote: true,
    institutionName: INSTITUTIONS.harvard.name,
    applicationUrl: 'https://example.edu/harvard-fellow',
    deadline: '2026-07-15',
    sponsored: false,
    description:
      '**Standalone** institution posting (demo). Policy + economics background; not lab-attached.',
  },
  {
    id: 'erudis_demo_job_07',
    labId: null,
    postedByUserId: U.profChen,
    title: 'Summer Undergraduate Research — NLP',
    positionType: 'Undergraduate',
    department: 'Computer Science',
    location: 'Stanford, CA',
    remote: false,
    institutionName: INSTITUTIONS.stanford.name,
    applicationUrl: null,
    deadline: '2026-03-01',
    sponsored: false,
    description:
      'URAP-style **summer** slot for Stanford undergrads (demo listing).',
  },
  {
    id: 'erudis_demo_job_08',
    labId: LAB.berkeley,
    postedByUserId: U.profBell,
    title: 'Lab Manager / Research Coordinator',
    positionType: 'Staff',
    department: 'Integrative Biology',
    location: 'Berkeley, CA',
    remote: false,
    institutionName: INSTITUTIONS.berkeley.name,
    applicationUrl: 'https://example.edu/berkeley-coordinator',
    deadline: null,
    sponsored: false,
    description:
      'Operations and **compliance** support for a growing wet-lab + compute group (demo).',
  },
];

const PAPERS = [
  {
    id: 'erudis_demo_paper_01',
    addedBy: U.profRivera,
    labId: LAB.mit,
    title: 'Certified robustness under covariate shift (demo)',
    authors: ['E. Rivera', 'J. Kim'],
    venue: 'Demo Conference on ML',
    publicationYear: 2025,
    arxivId: '2501.10001',
    resonateCount: 12,
    viewCount: 88,
  },
  {
    id: 'erudis_demo_paper_02',
    addedBy: U.profChen,
    labId: LAB.stanford,
    title: 'Sparse document encoders at 100k tokens',
    authors: ['J. Chen', 'M. Santos'],
    venue: 'Demo Workshop on NLP',
    publicationYear: 2024,
    doi: '10.0000/demo.2024.2',
    resonateCount: 18,
    viewCount: 210,
  },
  {
    id: 'erudis_demo_paper_03',
    addedBy: U.profBell,
    labId: LAB.berkeley,
    title: 'Bayesian deconvolution for spatial atlases',
    authors: ['A. Bell', 'R. Patel'],
    venue: 'Journal of Demo Data',
    publicationYear: 2023,
    url: 'https://example.com/paper-demo',
    resonateCount: 9,
    viewCount: 140,
  },
];

const RESEARCH_LOGS = [
  {
    userId: U.phdKim,
    date: '2026-01-08',
    type: 'experiment',
    title: 'Pilot run: calibration checklist',
    content: 'Baseline noise floor after recalibration (demo log).',
    isPublic: true,
    tags: ['methods'],
  },
  {
    userId: U.phdSantos,
    date: '2026-01-12',
    type: 'writing',
    title: 'Related work — agent benchmarks',
    content: 'Drafting survey section on tool-use evals.',
    isPublic: true,
    tags: ['writing'],
  },
  {
    userId: U.postdocLee,
    date: '2026-01-15',
    type: 'idea',
    title: 'Graph-biased attention sketch',
    content: 'Whiteboard notes for PI meeting.',
    isPublic: false,
    tags: ['hypothesis'],
  },
];

const COFFEE_CHATS = [
  {
    id: 'erudis_demo_coffee_01',
    fromUserId: U.phdKim,
    toUserId: U.profRivera,
    message: 'Would love to discuss thesis direction and lab rotation options.',
    status: 'pending',
    hoursAgo: 6,
  },
  {
    id: 'erudis_demo_coffee_02',
    fromUserId: U.phdSantos,
    toUserId: U.profChen,
    message: 'Interested in your work on LLM evaluation — free Thursday?',
    status: 'pending',
    hoursAgo: 12,
  },
  {
    id: 'erudis_demo_coffee_03',
    fromUserId: U.researcherWalsh,
    toUserId: U.profBell,
    message: 'Exploring collaboration on science-policy datasets.',
    status: 'accepted',
    hoursAgo: 48,
  },
  {
    id: 'erudis_demo_coffee_04',
    fromUserId: U.postdocLee,
    toUserId: U.profRivera,
    message: 'Quick sync on the graph-attention pilot?',
    status: 'declined',
    hoursAgo: 72,
  },
];

const RESEARCH_GRAPHS = [
  {
    userId: U.profRivera,
    loggedDates: ['2026-01-02', '2026-01-05', '2026-01-08', '2026-01-12'],
    currentStreak: 4,
    longestStreak: 21,
    totalLogDays: 48,
    last30DayCount: 8,
  },
  {
    userId: U.phdKim,
    loggedDates: ['2026-01-03', '2026-01-06', '2026-01-10', '2026-01-14', '2026-01-17'],
    currentStreak: 5,
    longestStreak: 12,
    totalLogDays: 31,
    last30DayCount: 11,
  },
];

module.exports = {
  INSTITUTIONS,
  INSTITUTION_DOCS,
  U,
  LAB,
  USERS,
  LABS,
  POSTS,
  JOBS,
  PAPERS,
  RESEARCH_LOGS,
  RESEARCH_GRAPHS,
  COFFEE_CHATS,
};
